site_name: ZEIT.IO Dokumentation
site_url: https://docs-de.zeit.io/
nav:
  - common:
    - 'Start': 'index.md'
    - 'Start': 'index.en.md'
  - employee_context:
    - common: 'mitarbeiter/common.md'
    - common: 'mitarbeiter/common.en.md'
  - freelancer_context:
    - 'Start': 'freiberufler/start.md'
    - 'Start2': 'freiberufler/start2.md'
  - approver_context:
    - 'Start': 'genehmiger/start.md'
    - 'Start2': 'genehmiger/start2.md'
  - organisations_context:
    - 'Start': 'organisationen/start.md'
    - 'Start2': 'organisationen/start2.md'
theme:
  name: material
  language: de
  palette:
    primary: green
  custom_dir: "overrides"

plugins:
  - search
  - i18n:
      languages:
        de: "Deutsch"
        en: "English"
      default_language: 'de'
      no_translation:
        en: "This page isn't translated to English."
        de: "Diese Seite ist nicht ins Deutsche übersetzt."
      translate_nav:
        de:
          common: "Allgemein"
          employee_context: "Mitarbeiter Kontext"
          freelancer_context: "Freiberufler Kontext"
          approver_context: "Genehmiger Kontext"
          organisations_context: "Organisations Kontext"
          page title: "ZEIT.IO Dokumentation"
        en:
          common: "Common"
          employee_context: "Employee context"
          freelancer_context: "Freelancer context"
          approver_context: "Approver context"
          organisations_context: "Organisations context"
          page title: "ZEIT.IO Documentation"


