on:
  push:
    branches:
      - prod-docs-deploy

name: Deploy docs to production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: build-image
        run: |
          pip install mkdocs mkdocs-material mkdocs-i18n;
          mkdocs build;

      - name: Upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "docs.zeit.io"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"
          SOURCE_DIR: "site"
